static_types:
    "unknown": 0
    "other": 1
    "bridge": 2
    "building": 3
    "house": 3
    "skyscraper" : 3
    "block" : 3
    "pole": 4
    "pylon": 5
    "delineator": 6
    "tree": 7
    "pine" : 7
    #"sassafras" : 7
    "patanus" : 7
    "barrier": 8
    "vegetation": 9
    "grass": 9
    "curbstone": 10
    "wall": 11
    "vertical_structure": 12
    "sculpture" : 12
    "lamppost" : 12
    "rectangular_structure": 13
    "overhead_structure": 14
    "reflective_structure": 15
    "construction_site_element": 16
exclude_names: ["SM_T03_Wall", "name2", "name3"] # Exclude specific objects from OBJ file
obj_file: "/home/kbrezhnyev/DATA/carla-export/Town02/Town02.obj" # Path to OBJ file. If commented, the OBJ file is skipped. Optional.
xodr_file: "/home/kbrezhnyev/DATA/carla-export/Town02/Town02.xodr" # Path to XODR file. Required.
map_name: "Town02" # Name of Carla map to be loaded.
fps: 10 # FPS of the Carla simulation. Depending on CPU/GPU the playback (rendering) may be faster or slower than the realtime.
realtime_playback: true # if set true, the Carla playback will be slowed down to render frames with 1/FPS rate. See FPS flag.
scale: 0.01 # Scale factor between OBJ and XODR. For standard Carla maps is 0.01.
number_vehicles: 50
number_walkers: 50
write_output: /home/kbrezhnyev/DATA/output.osi